services:
  - type: web
    name: intelliaudit-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LLM_PROVIDER
        value: gemini
      - key: PYTHON_VERSION
        value: 3.9.16 